namespace Riftbound.Engine;

public sealed record CardBehaviorDefinition(
    string CardNo,
    string DisplayName,
    int ManaCost,
    string EffectKind,
    int DamageAmount,
    int RequiredTargetCount,
    string DamageConditionKind = CardDamageConditionKinds.None,
    int ConditionalDamageAmount = 0,
    string StatusEffectId = "",
    int DrawCount = 0,
    bool DestroysTarget = false,
    string TargetScope = CardTargetScopes.BattlefieldUnit,
    int MinTargetCount = -1,
    string Mode = "",
    int EchoManaCost = 0,
    string DrawConditionKind = CardDrawConditionKinds.None,
    string DynamicDrawCountKind = CardDynamicDrawCountKinds.None,
    bool AllowsRepeatedTargets = false,
    string CostReductionConditionKind = CardCostReductionConditionKinds.None,
    int CostReductionMana = 0,
    string CostReductionUnitTag = "",
    bool RecyclesTargets = false,
    bool DamagesAllBattlefieldUnits = false,
    bool DamagesAllEnemyCombatUnits = false,
    bool DamagesAllEnemyBattlefieldUnits = false,
    bool DestroysAllEquipment = false,
    int OtherEnemyBattlefieldUnitsDamageAmount = 0,
    bool ModifiesAllFriendlyUnits = false,
    int MaxTargetPower = 0,
    string DrawRecipientKind = CardDrawRecipientKinds.Controller,
    bool DestroysAllUnits = false,
    bool ReturnsTargetToHand = false,
    bool ReturnsAllUnitsToHand = false,
    bool ReturnsAllFieldObjectsToHand = false,
    int PowerModifierAmount = 0,
    string PowerModifierConditionKind = CardPowerModifierConditionKinds.None,
    string PowerModifierUnitTag = "",
    string PowerModifierControlledUnitTags = "",
    int MinimumPowerAfterModifier = 0,
    bool BanishesIfDestroyedThisTurn = false,
    int RuneCallCount = 0,
    int DrawCountIfRuneCallFails = 0,
    int RuneCallCountAfterTargetReturn = 0,
    bool MovesTargetToBase = false,
    int SecondaryPowerModifierAmount = 0,
    bool ReadiesTarget = false,
    bool ReadiesAllFriendlyUnits = false,
    bool ExhaustsAllFriendlyUnits = false,
    bool DrawsBeforeRuneCall = false,
    bool ReturnsTargetToHandIfAlreadyHasStatusEffect = false,
    int EffectRepeatCountIfExhaustFriendlyUnitOptionalCost = 0,
    bool DiscardsTargetFromHand = false,
    bool ReturnsGraveyardTargetToHand = false,
    bool DealsMutualTargetPowerDamage = false,
    int CreatedBaseUnitTokenCount = 0,
    int CreatedBaseUnitTokenPower = 0,
    string CreatedBaseUnitTokenName = "",
    string CreatedBaseUnitTokenTags = "",
    bool CreatedBaseUnitTokenCopiesFirstTarget = false,
    bool DiscardsAllPlayersHandsThenDraws = false,
    bool RequiresDestroyFriendlyPowerfulUnitAdditionalCost = false,
    bool DestroysFirstTargetAndBuffsSecondByDestroyedPower = false,
    string SecondaryStatusEffectId = "",
    int EffectRepeatCountIfDiscardHandCardOptionalCost = 0,
    bool ReadiesFirstTargetAndDamagesSecondByFirstPower = false,
    bool SetsFirstTargetPowerToSecondIfLower = false,
    bool SwapsTargetPowersUntilEndOfTurn = false,
    string TargetOwnerMainDeckDestination = "",
    int MainDeckLookCount = 0,
    int MainDeckLookTargetStartIndex = 0,
    string MainDeckTargetRequiredTag = "",
    bool DrawsSelectedMainDeckTarget = false,
    bool RecyclesSelectedMainDeckTargets = false,
    bool RecyclesUnselectedMainDeckLookCards = false,
    bool UsesFriendlyBattlefieldUnitCountAsMaxTargetCount = false,
    bool UsesEnemyBattlefieldUnitCountAsPowerModifierMultiplier = false,
    int PowerModifierTargetIndex = -1,
    int StatusEffectTargetIndex = -1,
    string TargetForbiddenTag = "",
    bool ModifiesAllFriendlyBattlefieldUnits = false,
    bool ModifiesAllEnemyBattlefieldUnits = false,
    int MaxTotalTargetPower = 0,
    bool AppliesStatusEffectToAllUnits = false,
    bool MovesFirstTargetToSecondTargetLocation = false,
    string TargetRequiredTag = "",
    string AnyTargetRequiredTag = "",
    string TargetAddedTag = "",
    bool UsesTargetCurrentPowerAsPowerModifier = false,
    int CreatedBaseEquipmentTokenCount = 0,
    string CreatedBaseEquipmentTokenName = "",
    string CreatedBaseEquipmentTokenTags = "",
    bool CreatedBaseEquipmentTokenIsExhausted = false,
    int CreatedBaseEquipmentTokenCountIfDestroyedFriendlyUnit = 0,
    int CreatedBaseEquipmentTokenCountIfDestroyedEnemyUnit = 0,
    bool DamageAmountFromFirstTargetManaCost = false,
    bool DrawsControllerAndOtherPlayers = false,
    bool CallsRuneForControllerAndOtherPlayers = false,
    bool GrantsBoon = false,
    bool MovesTargetToBattlefield = false,
    bool GrantsBoonToAllFriendlyUnits = false,
    bool SwapsTargetLocations = false,
    bool DamagesAllEnemyBattlefieldUnitsByFirstTargetPower = false,
    bool MovesTargetsToOwnerBattlefields = false,
    bool DamageAmountFromOptionalPowerCost = false);

public static class CardDamageConditionKinds
{
    public const string None = "NONE";
    public const string ControllerHasFaceDownCard = "CONTROLLER_HAS_FACE_DOWN_CARD";
    public const string TargetIsAttacking = "TARGET_IS_ATTACKING";
}

public static class CardTargetScopes
{
    public const string BattlefieldUnit = "BATTLEFIELD_UNIT";
    public const string BattlefieldUnitOrEquipment = "BATTLEFIELD_UNIT_OR_EQUIPMENT";
    public const string BaseUnit = "BASE_UNIT";
    public const string AnyUnit = "ANY_UNIT";
    public const string FriendlyUnit = "FRIENDLY_UNIT";
    public const string FriendlyUnitThenFriendlyUnit = "FRIENDLY_UNIT_THEN_FRIENDLY_UNIT";
    public const string FriendlyThenEnemyUnits = "FRIENDLY_THEN_ENEMY_UNITS";
    public const string FriendlyEquipmentThenEnemyEquipment = "FRIENDLY_EQUIPMENT_THEN_ENEMY_EQUIPMENT";
    public const string FriendlyThenEnemyBattlefieldUnits = "FRIENDLY_THEN_ENEMY_BATTLEFIELD_UNITS";
    public const string FriendlyBattlefieldThenEnemyBattlefieldUnits = "FRIENDLY_BATTLEFIELD_THEN_ENEMY_BATTLEFIELD_UNITS";
    public const string AnyUnitThenFriendlyMainDeckCard = "ANY_UNIT_THEN_FRIENDLY_MAIN_DECK_CARD";
    public const string FriendlyBattlefieldUnit = "FRIENDLY_BATTLEFIELD_UNIT";
    public const string FriendlyHandCard = "FRIENDLY_HAND_CARD";
    public const string FriendlyHandCardThenBattlefieldUnit = "FRIENDLY_HAND_CARD_THEN_BATTLEFIELD_UNIT";
    public const string FriendlyMainDeckCard = "FRIENDLY_MAIN_DECK_CARD";
    public const string FriendlyGraveyardCard = "FRIENDLY_GRAVEYARD_CARD";
    public const string AttackingUnit = "ATTACKING_UNIT";
    public const string EnemyAttackingUnit = "ENEMY_ATTACKING_UNIT";
    public const string EnemyBattlefieldUnit = "ENEMY_BATTLEFIELD_UNIT";
    public const string EnemyUnit = "ENEMY_UNIT";
    public const string EnemyUnitThenEnemyUnit = "ENEMY_UNIT_THEN_ENEMY_UNIT";
    public const string OpponentHandCard = "OPPONENT_HAND_CARD";
    public const string OpponentGraveyardCard = "OPPONENT_GRAVEYARD_CARD";
    public const string FriendlyBaseUnit = "FRIENDLY_BASE_UNIT";
    public const string Equipment = "EQUIPMENT";
}

public static class CardObjectTags
{
    public const string UnitCard = "CARD_TYPE:UNIT";
    public const string EquipmentCard = "CARD_TYPE:EQUIPMENT";
    public const string Spellshield = "法盾";
    public const string Standby = "待命";
    public const string Ephemeral = "瞬息";
    public const string SandSoldier = "黄沙士兵";
    public const string Boon = "增益";
}

public static class CardDrawConditionKinds
{
    public const string None = "NONE";
    public const string TargetDestroyedByThisEffect = "TARGET_DESTROYED_BY_THIS_EFFECT";
}

public static class CardDynamicDrawCountKinds
{
    public const string None = "NONE";
    public const string ControllerPowerfulUnits = "CONTROLLER_POWERFUL_UNITS";
}

public static class CardDrawRecipientKinds
{
    public const string Controller = "CONTROLLER";
    public const string TargetController = "TARGET_CONTROLLER";
}

public static class CardCostReductionConditionKinds
{
    public const string None = "NONE";
    public const string EnemyUnitDestroyedThisTurn = "ENEMY_UNIT_DESTROYED_THIS_TURN";
    public const string ControllerHighestUnitPower = "CONTROLLER_HIGHEST_UNIT_POWER";
    public const string OpponentWithinThreeOfWinningScore = "OPPONENT_WITHIN_THREE_OF_WINNING_SCORE";
    public const string ControllerControlsTaggedUnit = "CONTROLLER_CONTROLS_TAGGED_UNIT";
}

public static class CardPowerModifierConditionKinds
{
    public const string None = "NONE";
    public const string TargetIsAttacking = "TARGET_IS_ATTACKING";
    public const string TargetIsDefending = "TARGET_IS_DEFENDING";
}

public static class CardBehaviorRegistry
{
    private static readonly CardBehaviorDefinition[] Definitions =
    [
        new(
            "UNL-007/219",
            "惩戒",
            2,
            "PUNISHMENT_DAMAGE_3",
            3,
            1,
            TargetScope: CardTargetScopes.BattlefieldUnit,
            BanishesIfDestroyedThisTurn: true),
        new(
            "UNL-014/219",
            "渊海狩咒",
            1,
            "ABYSSAL_HUNT_DAMAGE_2",
            2,
            1,
            CardDamageConditionKinds.ControllerHasFaceDownCard,
            4),
        new(
            "UNL-013/219",
            "莲花陷阱",
            2,
            "LOTUS_TRAP_DOUBLE_DAMAGE_RECEIVED_THIS_TURN",
            0,
            1,
            StatusEffectId: "DAMAGE_RECEIVED_DOUBLED_THIS_TURN",
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "UNL-020/219",
            "曼舞手雷",
            2,
            "DANCING_GRENADE_DAMAGE_2_NO_RECAST",
            2,
            1,
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "OGS·003/024",
            "焚烧",
            2,
            "INCINERATE_DAMAGE_2",
            2,
            1),
        new(
            "OGS·002/024",
            "烈火风暴",
            6,
            "FIRESTORM_DAMAGE_ALL_ENEMY_BATTLEFIELD_UNITS_3",
            3,
            0,
            DamagesAllEnemyBattlefieldUnits: true),
        new(
            "OGN·268/298",
            "弹幕时间",
            1,
            "BULLET_TIME_DAMAGE_ENEMY_BATTLEFIELD_UNITS_BY_POWER_SPENT",
            0,
            0,
            DamagesAllEnemyBattlefieldUnits: true,
            DamageAmountFromOptionalPowerCost: true),
        new(
            "UNL-072/219",
            "新月打击",
            3,
            "CRESCENT_STRIKE_DAMAGE_TARGET_4_OTHER_ENEMY_BATTLEFIELD_1",
            4,
            1,
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit,
            OtherEnemyBattlefieldUnitsDamageAmount: 1),
        new(
            "OGN·266/298",
            "虹吸能量",
            2,
            "SIPHON_ENERGY_FRIENDLY_BATTLEFIELD_PLUS_1_ENEMY_BATTLEFIELD_MINUS_1",
            0,
            0,
            PowerModifierAmount: 1,
            SecondaryPowerModifierAmount: -1,
            MinimumPowerAfterModifier: 1,
            ModifiesAllFriendlyBattlefieldUnits: true,
            ModifiesAllEnemyBattlefieldUnits: true),
        new(
            "UNL-198/219",
            "月之降临",
            3,
            "MOON_RISE_ENEMY_BATTLEFIELD_MINUS_2_NO_MOVE",
            0,
            0,
            PowerModifierAmount: -2,
            ModifiesAllEnemyBattlefieldUnits: true),
        new(
            "OGN·050/298",
            "符文禁锢",
            2,
            "RUNE_PRISON_STUN_UNIT",
            0,
            1,
            CardDamageConditionKinds.None,
            0,
            "STUNNED",
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "UNL-042/219",
            "走开",
            3,
            "STAY_AWAY_STUN_DRAW_1",
            0,
            1,
            CardDamageConditionKinds.None,
            0,
            "STUNNED",
            1,
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "SFD·040/221",
            "扑咚！",
            2,
            "KERPLUNK_STUN_ATTACKING_UNIT",
            0,
            1,
            CardDamageConditionKinds.None,
            0,
            "STUNNED",
            TargetScope: CardTargetScopes.AttackingUnit,
            EchoManaCost: 2),
        new(
            "UNL-134/219",
            "存在焦虑",
            1,
            "EXISTENTIAL_DREAD_STUN_ATTACKING_ENEMY_OR_RETURN_STUNNED",
            0,
            1,
            CardDamageConditionKinds.None,
            0,
            "STUNNED",
            TargetScope: CardTargetScopes.EnemyAttackingUnit,
            EchoManaCost: 2,
            ReturnsTargetToHandIfAlreadyHasStatusEffect: true),
        new(
            "OGN·262/298",
            "天顶之刃",
            3,
            "ZENITH_BLADE_STUN_ENEMY_BATTLEFIELD_UNIT_NO_MOVE",
            0,
            1,
            CardDamageConditionKinds.None,
            0,
            "STUNNED",
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit),
        new(
            "OGN·053/298",
            "秘奥义！慈悲度魂落",
            3,
            "SECRET_ART_MERCY_GRANT_BOON_NO_GLOBAL_BONUS",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyUnit,
            GrantsBoon: true),
        new(
            "OGN·270/298",
            "叹为观止",
            1,
            "STUNNING_DISPLAY_GRANT_BOON_MOVE_BASE_UNIT_TO_BATTLEFIELD",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyBaseUnit,
            GrantsBoon: true,
            MovesTargetToBattlefield: true),
        new(
            "OGN·153/298",
            "公开行动",
            5,
            "OPEN_ACTION_GRANT_BOON_ALL_FRIENDLY_UNITS_NO_CONSUME",
            0,
            0,
            GrantsBoonToAllFriendlyUnits: true),
        new(
            "OGN·250/298",
            "天声震落",
            6,
            "THUNDERING_DROP_BASE_UNIT_POWER_DAMAGE_ENEMY_BATTLEFIELD_MOVE",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyBaseUnit,
            MovesTargetToBattlefield: true,
            DamagesAllEnemyBattlefieldUnitsByFirstTargetPower: true),
        new(
            "OGN·220/298",
            "强手裂颅",
            2,
            "SKULLCRACK_STUN_FRIENDLY_AND_ENEMY_BATTLEFIELD_UNITS",
            0,
            2,
            StatusEffectId: "STUNNED",
            TargetScope: CardTargetScopes.FriendlyBattlefieldThenEnemyBattlefieldUnits),
        new(
            "UNL-155/219",
            "英勇冲锋",
            3,
            "HEROIC_CHARGE_FRIENDLY_POWER_PLUS_1_STUN_ENEMY",
            0,
            2,
            StatusEffectId: "STUNNED",
            TargetScope: CardTargetScopes.FriendlyBattlefieldThenEnemyBattlefieldUnits,
            PowerModifierAmount: 1,
            PowerModifierTargetIndex: 0,
            StatusEffectTargetIndex: 1),
        new(
            "OGN·033/298",
            "巧取豪夺",
            2,
            "HIGHWAY_ROBBERY_DAMAGE_6_NO_DRAW_CHOICE",
            6,
            1,
            TargetScope: CardTargetScopes.EnemyUnit),
        new(
            "UNL-073/219",
            "致命华彩",
            4,
            "DEADLY_FLOURISH_DAMAGE_3_NO_GOLD_TRIGGER",
            3,
            1,
            TargetScope: CardTargetScopes.EnemyUnit),
        new(
            "OGN·033/298",
            "巧取豪夺",
            2,
            "HIGHWAY_ROBBERY_DRAW_2_TARGET_CONTROLLER_CHOICE",
            0,
            1,
            DrawCount: 2,
            TargetScope: CardTargetScopes.EnemyUnit,
            Mode: "TARGET_CONTROLLER_CHOOSES_DRAW_2"),
        new(
            "OGN·260/298",
            "狂风绝息斩",
            3,
            "LAST_BREATH_READY_FRIENDLY_DAMAGE_ENEMY_BY_POWER",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyThenEnemyBattlefieldUnits,
            ReadiesFirstTargetAndDamagesSecondByFirstPower: true),
        new(
            "OGN·108/298",
            "聚合变异",
            2,
            "CONVERGENT_MUTATION_MATCH_FRIENDLY_POWER_IF_LOWER",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyUnit,
            SetsFirstTargetPowerToSecondIfLower: true),
        new(
            "SFD·145/221",
            "换换乐",
            2,
            "SWITCHEROO_SWAP_TWO_BATTLEFIELD_UNIT_POWERS",
            0,
            2,
            TargetScope: CardTargetScopes.BattlefieldUnit,
            SwapsTargetPowersUntilEndOfTurn: true),
        new(
            "SFD·001/221",
            "矢志不退",
            2,
            "STAND_DEFIANT_POWER_PER_ENEMY_BATTLEFIELD_UNIT",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyBattlefieldUnit,
            PowerModifierAmount: 2,
            UsesEnemyBattlefieldUnitCountAsPowerModifierMultiplier: true),
        new(
            "SFD·005/221",
            "印爆术",
            1,
            "SIGIL_BURST_DESTROY_EQUIPMENT_TARGET_CONTROLLER_DRAW_2",
            0,
            1,
            DrawCount: 2,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.Equipment,
            DrawRecipientKind: CardDrawRecipientKinds.TargetController),
        new(
            "SFD·017/221",
            "雷霆突降",
            3,
            "THUNDERING_DROP_DAMAGE_2_OR_4_ATTACKING",
            2,
            1,
            CardDamageConditionKinds.TargetIsAttacking,
            4),
        new(
            "SFD·070/221",
            "痛苦之酬",
            3,
            "PAINFUL_PAYOFF_DAMAGE_3_CREATE_GOLD_EQUIPMENT",
            3,
            1,
            TargetScope: CardTargetScopes.BattlefieldUnit,
            CreatedBaseEquipmentTokenCount: 1,
            CreatedBaseEquipmentTokenName: "金币",
            CreatedBaseEquipmentTokenTags: CardObjectTags.EquipmentCard,
            CreatedBaseEquipmentTokenIsExhausted: true),
        new(
            "SFD·004/221",
            "丛林伏击",
            2,
            "JUNGLE_AMBUSH_CREATE_GOLD_EQUIPMENT",
            0,
            0,
            CreatedBaseEquipmentTokenCount: 1,
            CreatedBaseEquipmentTokenName: "金币",
            CreatedBaseEquipmentTokenTags: CardObjectTags.EquipmentCard,
            CreatedBaseEquipmentTokenIsExhausted: true),
        new(
            "SFD·162/221",
            "血钱",
            2,
            "BLOOD_MONEY_DESTROY_SMALL_BATTLEFIELD_UNIT_CREATE_GOLD",
            0,
            1,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.BattlefieldUnit,
            MaxTargetPower: 2,
            CreatedBaseEquipmentTokenName: "金币",
            CreatedBaseEquipmentTokenTags: CardObjectTags.EquipmentCard,
            CreatedBaseEquipmentTokenIsExhausted: true,
            CreatedBaseEquipmentTokenCountIfDestroyedFriendlyUnit: 2,
            CreatedBaseEquipmentTokenCountIfDestroyedEnemyUnit: 1),
        new(
            "SFD·023/221",
            "透体圣光",
            2,
            "PIERCING_LIGHT_DAMAGE_2_UP_TO_2_BATTLEFIELD_UNITS",
            2,
            2,
            TargetScope: CardTargetScopes.BattlefieldUnit,
            MinTargetCount: 1),
        new(
            "OGN·009/298",
            "海克斯射线",
            1,
            "HEXTECH_RAY_DAMAGE_3",
            3,
            1),
        new(
            "OGN·014/298",
            "霹天雳地",
            8,
            "THUNDERING_SKY_DAMAGE_5",
            5,
            1,
            CostReductionConditionKind: CardCostReductionConditionKinds.ControllerHighestUnitPower,
            CostReductionMana: 8),
        new(
            "OGN·005/298",
            "碎裂之火",
            4,
            "SHATTERED_FIRE_DAMAGE_3_DRAW_IF_DESTROYED",
            3,
            1,
            DrawCount: 1,
            DrawConditionKind: CardDrawConditionKinds.TargetDestroyedByThisEffect),
        new(
            "OGN·008/298",
            "罪恶快感",
            2,
            "SINFUL_PLEASURE_DISCARD_HAND_CARD_DAMAGE_MANA_COST",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyHandCardThenBattlefieldUnit,
            DiscardsTargetFromHand: true,
            DamageAmountFromFirstTargetManaCost: true),
        new(
            "OGN·029/298",
            "星落",
            2,
            "STARFALL_DAMAGE_3_TWICE",
            3,
            2,
            TargetScope: CardTargetScopes.AnyUnit,
            AllowsRepeatedTargets: true),
        new(
            "OGN·128/298",
            "决斗",
            2,
            "DUEL_MUTUAL_POWER_DAMAGE",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyThenEnemyUnits,
            DealsMutualTargetPowerDamage: true),
        new(
            "OGS·008/024",
            "绅士决斗",
            6,
            "GENTLEMAN_DUEL_POWER_PLUS_3_THEN_MUTUAL_POWER_DAMAGE",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyThenEnemyUnits,
            PowerModifierAmount: 3,
            DealsMutualTargetPowerDamage: true),
        new(
            "SFD·114/221",
            "行军号令",
            3,
            "MARCHING_ORDERS_MUTUAL_POWER_DAMAGE",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyThenEnemyBattlefieldUnits,
            EchoManaCost: 3,
            DealsMutualTargetPowerDamage: true),
        new(
            "UNL-110/219",
            "巨人之战",
            6,
            "CLASH_OF_GIANTS_MUTUAL_POWER_DAMAGE",
            0,
            2,
            TargetScope: CardTargetScopes.AnyUnit,
            DealsMutualTargetPowerDamage: true),
        new(
            "OGN·248/298",
            "艾卡西亚暴雨",
            7,
            "ICATHIAN_RAIN_DAMAGE_2_SIX_TIMES",
            2,
            6,
            TargetScope: CardTargetScopes.AnyUnit,
            AllowsRepeatedTargets: true),
        new(
            "OGN·133/298",
            "剑刃飓风",
            1,
            "BLADE_WHIRLWIND_DAMAGE_ALL_BATTLEFIELD_UNITS_1",
            1,
            0,
            DamagesAllBattlefieldUnits: true),
        new(
            "OGN·127/298",
            "加农炮幕",
            2,
            "CANNON_BARRAGE_DAMAGE_ALL_ENEMY_COMBAT_UNITS_2",
            2,
            0,
            DamagesAllEnemyCombatUnits: true),
        new(
            "OGN·123/298",
            "过载能量",
            7,
            "OVERCHARGED_ENERGY_EXHAUST_ALL_FRIENDLY_DAMAGE_ALL_BATTLEFIELD_12",
            12,
            0,
            DamagesAllBattlefieldUnits: true,
            ExhaustsAllFriendlyUnits: true),
        new(
            "OGN·085/298",
            "彗星坠击",
            5,
            "COMET_STRIKE_DAMAGE_6",
            6,
            1),
        new(
            "OGS·022/024",
            "终极闪光",
            8,
            "FINAL_SPARK_DAMAGE_8",
            8,
            1,
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "OGS·024/024",
            "致命打击",
            5,
            "DECISIVE_STRIKE_ALL_FRIENDLY_POWER_PLUS_2",
            0,
            0,
            ModifiesAllFriendlyUnits: true,
            PowerModifierAmount: 2),
        new(
            "OGN·252/298",
            "超究极死神飞弹！",
            4,
            "SUPER_MEGA_DEATH_ROCKET_DAMAGE_5",
            5,
            1,
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "OGN·254/298",
            "诺克萨斯断头台",
            4,
            "NOXIAN_GUILLOTINE_DESTROY_ON_NEXT_DAMAGE",
            0,
            1,
            StatusEffectId: "DESTROY_ON_NEXT_DAMAGE_THIS_TURN",
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "OGN·221/298",
            "帝国谕令",
            5,
            "IMPERIAL_DECREE_ALL_UNITS_DESTROY_ON_DAMAGE_THIS_TURN",
            0,
            0,
            StatusEffectId: "DESTROY_ON_NEXT_DAMAGE_THIS_TURN",
            AppliesStatusEffectToAllUnits: true),
        new(
            "OGS·012/024",
            "爆能术",
            6,
            "DETONATION_DESTROY_BATTLEFIELD_UNIT",
            0,
            1,
            DestroysTarget: true),
        new(
            "UNL-159/219",
            "狩魂",
            2,
            "HUNT_THE_WEAK_DESTROY_BATTLEFIELD_UNIT_POWER_3_OR_LESS",
            0,
            1,
            DestroysTarget: true,
            MaxTargetPower: 3),
        new(
            "SFD·164/221",
            "流沙陷坑",
            5,
            "QUICKSAND_PIT_DESTROY_BATTLEFIELD_UNIT",
            0,
            1,
            DestroysTarget: true),
        new(
            "OGN·213/298",
            "暗刃",
            2,
            "DARKIN_BLADE_DESTROY_BATTLEFIELD_UNIT_TARGET_CONTROLLER_DRAW_2",
            0,
            1,
            DrawCount: 2,
            DestroysTarget: true,
            DrawRecipientKind: CardDrawRecipientKinds.TargetController),
        new(
            "OGN·237/298",
            "国王诏令",
            6,
            "KINGS_EDICT_DESTROY_OTHER_PLAYER_CHOSEN_ENEMY_UNIT",
            0,
            1,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.EnemyUnit),
        new(
            "OGN·256/298",
            "妖异狐火",
            3,
            "SPIRIT_FIRE_DESTROY_BATTLEFIELD_UNITS_TOTAL_POWER_4",
            0,
            4,
            DestroysTarget: true,
            MinTargetCount: 0,
            MaxTotalTargetPower: 4),
        new(
            "UNL-180/219",
            "破败之咒",
            9,
            "RUINATION_DESTROY_ALL_UNITS",
            0,
            0,
            DestroysAllUnits: true),
        new(
            "UNL-182/219",
            "完美谢幕",
            4,
            "PERFECT_FINALE_DRAW_1",
            0,
            0,
            Mode: "DRAW_1",
            DrawCount: 1),
        new(
            "UNL-182/219",
            "完美谢幕",
            4,
            "PERFECT_FINALE_BATTLEFIELD_DAMAGE_2",
            2,
            1,
            Mode: "BATTLEFIELD_UNIT_DAMAGE_2"),
        new(
            "UNL-182/219",
            "完美谢幕",
            4,
            "PERFECT_FINALE_BASE_DAMAGE_3",
            3,
            1,
            TargetScope: CardTargetScopes.BaseUnit,
            Mode: "BASE_UNIT_DAMAGE_3"),
        new(
            "UNL-182/219",
            "完美谢幕",
            4,
            "PERFECT_FINALE_BATTLEFIELD_POWER_MINUS_4",
            0,
            1,
            Mode: "BATTLEFIELD_UNIT_POWER_MINUS_4",
            PowerModifierAmount: -4),
        new(
            "SFD·147/221",
            "坠渊之流",
            8,
            "UNDERTOW_RETURN_ALL_UNITS_AND_EQUIPMENT_TO_HAND",
            0,
            0,
            ReturnsAllFieldObjectsToHand: true),
        new(
            "OGN·179/298",
            "折戟再战",
            1,
            "BROKEN_BLADES_REMATCH_DESTROY_EACH_PLAYER_EQUIPMENT",
            0,
            2,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.FriendlyEquipmentThenEnemyEquipment),
        new(
            "UNL-061/219",
            "台前作秀",
            2,
            "CENTER_STAGE_DRAW_1",
            0,
            0,
            DrawCount: 1,
            EchoManaCost: 2),
        new(
            "UNL-009/219",
            "大幕渐起",
            2,
            "THE_CURTAIN_RISES_READY_UNIT",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            EchoManaCost: 2,
            ReadiesTarget: true),
        new(
            "UNL-091/219",
            "聚心凝神",
            5,
            "CENTER_YOUR_MIND_DRAW_2",
            0,
            0,
            DrawCount: 2),
        new(
            "UNL-173/219",
            "牺牲",
            1,
            "SACRIFICE_DESTROY_FRIENDLY_POWERFUL_DRAW_2_CALL_RUNE",
            0,
            0,
            DrawCount: 2,
            RuneCallCount: 1,
            DrawsBeforeRuneCall: true,
            RequiresDestroyFriendlyPowerfulUnitAdditionalCost: true),
        new(
            "SFD·163/221",
            "断魂一扼",
            2,
            "SOUL_STRANGLE_DESTROY_FRIENDLY_POWER_BUFF_DRAW_1",
            0,
            2,
            DrawCount: 1,
            TargetScope: CardTargetScopes.FriendlyUnit,
            DestroysFirstTargetAndBuffsSecondByDestroyedPower: true),
        new(
            "OGN·209/298",
            "清理门户",
            2,
            "HOUSECLEANING_DESTROY_EACH_PLAYER_UNIT",
            0,
            2,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.FriendlyThenEnemyUnits),
        new(
            "SFD·182/221",
            "危险温度",
            1,
            "DANGER_TEMPERATURE_MECHANICAL_POWER_PLUS_1",
            0,
            0,
            ModifiesAllFriendlyUnits: true,
            PowerModifierAmount: 1,
            PowerModifierUnitTag: "机械"),
        new(
            "SFD·166/221",
            "集结部队",
            2,
            "ASSEMBLE_THE_RANKS_DRAW_1_NO_UNIT_PLAYED",
            0,
            0,
            DrawCount: 1),
        new(
            "OGN·129/298",
            "迎敌号令",
            2,
            "CALL_TO_ACTION_DRAW_1_NO_UNIT_PLAYED",
            0,
            0,
            DrawCount: 1),
        new(
            "OGN·156/298",
            "暗中破坏",
            1,
            "COVERT_SABOTAGE_RECYCLE_OPPONENT_NON_UNIT_HAND_CARD",
            0,
            1,
            TargetScope: CardTargetScopes.OpponentHandCard,
            RecyclesTargets: true,
            TargetForbiddenTag: CardObjectTags.UnitCard),
        new(
            "UNL-103/219",
            "处置命令",
            2,
            "DISPOSAL_ORDER_DRAW_1",
            0,
            0,
            DrawCount: 1,
            Mode: "DRAW_1"),
        new(
            "UNL-103/219",
            "处置命令",
            2,
            "DISPOSAL_ORDER_RECYCLE_OPPONENT_GRAVEYARD_UP_TO_3",
            0,
            3,
            TargetScope: CardTargetScopes.OpponentGraveyardCard,
            MinTargetCount: 0,
            Mode: "RECYCLE_OPPONENT_GRAVEYARD_UP_TO_3",
            RecyclesTargets: true),
        new(
            "OGN·071/298",
            "次元门狂欢",
            3,
            "PORTALPALOOZA_OTHER_PLAYERS_CHOOSE_CARDS",
            0,
            0,
            DrawCount: 1,
            Mode: "OTHER_PLAYERS_CHOOSE_CARDS",
            DrawsControllerAndOtherPlayers: true),
        new(
            "OGN·071/298",
            "次元门狂欢",
            3,
            "PORTALPALOOZA_OTHER_PLAYERS_CHOOSE_RUNES",
            0,
            0,
            RuneCallCount: 1,
            Mode: "OTHER_PLAYERS_CHOOSE_RUNES",
            CallsRuneForControllerAndOtherPlayers: true),
        new(
            "SFD·122/221",
            "预判攻势",
            0,
            "PREDICTIVE_OFFENSIVE_DRAW_ONE_RECYCLE_OTHER",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyMainDeckCard,
            MainDeckLookCount: 2,
            DrawsSelectedMainDeckTarget: true,
            RecyclesUnselectedMainDeckLookCards: true),
        new(
            "OGN·183/298",
            "卡牌骗术",
            1,
            "CARD_TRICK_DRAW_ONE_RECYCLE_REST",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyMainDeckCard,
            MainDeckLookCount: 3,
            DrawsSelectedMainDeckTarget: true,
            RecyclesUnselectedMainDeckLookCards: true),
        new(
            "UNL-032/219",
            "龙虎双雄",
            2,
            "DRAGON_TIGER_DRAW_UNIT_RECYCLE_REST_NO_ECHO",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyMainDeckCard,
            MinTargetCount: 0,
            MainDeckLookCount: 3,
            MainDeckTargetRequiredTag: CardObjectTags.UnitCard,
            DrawsSelectedMainDeckTarget: true,
            RecyclesUnselectedMainDeckLookCards: true),
        new(
            "OGN·062/298",
            "增援",
            5,
            "REINFORCEMENTS_NO_SELECTION_RECYCLE_TOP_FIVE",
            0,
            0,
            TargetScope: CardTargetScopes.FriendlyMainDeckCard,
            MinTargetCount: 0,
            MainDeckLookCount: 5,
            DrawsSelectedMainDeckTarget: true,
            RecyclesUnselectedMainDeckLookCards: true),
        new(
            "OGN·048/298",
            "冥想",
            2,
            "MEDITATION_DRAW_1",
            0,
            0,
            DrawCount: 1,
            EffectRepeatCountIfExhaustFriendlyUnitOptionalCost: 2),
        new(
            "OGN·224/298",
            "废物利用",
            2,
            "SALVAGE_DESTROY_OPTIONAL_EQUIPMENT_DRAW_1",
            0,
            1,
            DrawCount: 1,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.Equipment,
            MinTargetCount: 0),
        new(
            "UNL-015/219",
            "占山为王",
            3,
            "KING_OF_THE_HILL_DRAW_1_NO_CONTROLLED_BATTLEFIELDS",
            0,
            0,
            DrawCount: 1),
        new(
            "UNL-125/219",
            "月神恩赐",
            3,
            "MOONSILVER_GIFT_DISCARD_1_DRAW_2",
            0,
            1,
            DrawCount: 2,
            TargetScope: CardTargetScopes.FriendlyHandCard,
            DiscardsTargetFromHand: true),
        new(
            "OGN·170/298",
            "亡者复生",
            2,
            "REVIVE_FROM_GRAVEYARD_TO_HAND",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyGraveyardCard,
            ReturnsGraveyardTargetToHand: true),
        new(
            "OGN·264/298",
            "游击战",
            2,
            "GUERRILLA_WARFARE_RETURN_STANDBY_GRAVEYARD_TO_HAND",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyGraveyardCard,
            MinTargetCount: 0,
            TargetRequiredTag: CardObjectTags.Standby,
            ReturnsGraveyardTargetToHand: true),
        new(
            "UNL-070/219",
            "化为灰烬",
            2,
            "ASHES_TO_ASHES_EQUIPMENT_EPHEMERAL",
            0,
            1,
            TargetScope: CardTargetScopes.Equipment,
            TargetAddedTag: CardObjectTags.Ephemeral),
        new(
            "UNL-165/219",
            "暗影的召唤",
            2,
            "CALL_OF_THE_SHADOWS_GIVE_EPHEMERAL_DRAW_2",
            0,
            1,
            DrawCount: 2,
            TargetScope: CardTargetScopes.FriendlyUnit,
            TargetForbiddenTag: CardObjectTags.Ephemeral,
            TargetAddedTag: CardObjectTags.Ephemeral),
        new(
            "OGN·180/298",
            "逝水如镜",
            4,
            "FLOWING_TIME_MIRROR_UNIT_OR_EQUIPMENT_EPHEMERAL",
            0,
            1,
            TargetScope: CardTargetScopes.BattlefieldUnitOrEquipment,
            TargetAddedTag: CardObjectTags.Ephemeral),
        new(
            "OGN·069/298",
            "背水一战",
            3,
            "BACK_AGAINST_WALL_DOUBLE_POWER_EPHEMERAL",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyUnit,
            TargetAddedTag: CardObjectTags.Ephemeral,
            UsesTargetCurrentPowerAsPowerModifier: true),
        new(
            "OGN·083/298",
            "借鉴历史",
            4,
            "BORROWED_HISTORY_DRAW_2",
            0,
            0,
            DrawCount: 2),
        new(
            "SFD·188/221",
            "虚空猛冲",
            2,
            "VOID_RUSH_DRAW_TWO_NO_FREE_PLAY",
            0,
            0,
            DrawCount: 2),
        new(
            "UNL-083/219",
            "镜中幻影",
            2,
            "REFLECTIONS_SWAP_FRIENDLY_UNITS_DRAW_1",
            0,
            2,
            DrawCount: 1,
            TargetScope: CardTargetScopes.FriendlyUnitThenFriendlyUnit,
            AnyTargetRequiredTag: CardObjectTags.Ephemeral,
            SwapsTargetLocations: true),
        new(
            "OGN·046/298",
            "决斗架势",
            1,
            "DUELING_STANCE_FRIENDLY_POWER_PLUS_1_BASE",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyUnit,
            PowerModifierAmount: 1),
        new(
            "UNL-031/219",
            "实战经验",
            1,
            "PRACTICAL_EXPERIENCE_POWER_PLUS_1",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 1),
        new(
            "UNL-046/219",
            "动物之友",
            1,
            "ANIMAL_FRIENDS_POWER_PER_CONTROLLED_TAG",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierControlledUnitTags: "鸟类|猫科|犬形|魄罗"),
        new(
            "OGN·058/298",
            "训练有素",
            2,
            "WELL_TRAINED_POWER_PLUS_2_DRAW_1",
            0,
            1,
            DrawCount: 1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 2),
        new(
            "OGN·093/298",
            "烟幕弹",
            2,
            "SMOKE_BOMB_POWER_MINUS_4_MIN_1",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: -4,
            MinimumPowerAfterModifier: 1),
        new(
            "OGN·095/298",
            "“敲”诈",
            1,
            "EXTORTION_POWER_MINUS_1_MIN_1_DRAW_1",
            0,
            1,
            DrawCount: 1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: -1,
            MinimumPowerAfterModifier: 1),
        new(
            "UNL-063/219",
            "月蚀",
            3,
            "ECLIPSE_POWER_MINUS_4_OPTIONAL_INSIGHT",
            0,
            2,
            TargetScope: CardTargetScopes.AnyUnitThenFriendlyMainDeckCard,
            MinTargetCount: 1,
            PowerModifierAmount: -4,
            MainDeckLookCount: 1,
            MainDeckLookTargetStartIndex: 1,
            RecyclesSelectedMainDeckTargets: true),
        new(
            "UNL-066/219",
            "月光之殇",
            7,
            "MOONFALL_POWER_MINUS_10",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: -10),
        new(
            "OGN·004/298",
            "顺劈",
            1,
            "CLEAVE_OVERWHELM_3",
            0,
            1,
            StatusEffectId: "OVERWHELM_3",
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 3,
            PowerModifierConditionKind: CardPowerModifierConditionKinds.TargetIsAttacking),
        new(
            "SFD·003/221",
            "血性冲刺",
            1,
            "BLOOD_RUSH_OVERWHELM_2",
            0,
            1,
            StatusEffectId: "OVERWHELM_2",
            TargetScope: CardTargetScopes.AnyUnit,
            EchoManaCost: 1,
            PowerModifierAmount: 2,
            PowerModifierConditionKind: CardPowerModifierConditionKinds.TargetIsAttacking),
        new(
            "UNL-010/219",
            "强能冲拳",
            1,
            "POWER_PUNCH_OVERWHELM_2_ROAM",
            0,
            1,
            StatusEffectId: "OVERWHELM_2",
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 2,
            PowerModifierConditionKind: CardPowerModifierConditionKinds.TargetIsAttacking,
            SecondaryStatusEffectId: "ROAM"),
        new(
            "OGN·057/298",
            "格挡",
            2,
            "PARRY_STEADFAST_3_BARRIER",
            0,
            1,
            StatusEffectId: "STEADFAST_3",
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 3,
            PowerModifierConditionKind: CardPowerModifierConditionKinds.TargetIsDefending,
            SecondaryStatusEffectId: "BARRIER"),
        new(
            "UNL-017/219",
            "怒吼清算",
            4,
            "ROARING_RECKONING_DISCARD_ECHO_OVERWHELM_4",
            0,
            1,
            StatusEffectId: "OVERWHELM_4",
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 4,
            PowerModifierConditionKind: CardPowerModifierConditionKinds.TargetIsAttacking,
            EffectRepeatCountIfDiscardHandCardOptionalCost: 2),
        new(
            "SFD·034/221",
            "蛮荒之力",
            2,
            "SAVAGE_STRENGTH_POWER_PLUS_2",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            EchoManaCost: 2,
            PowerModifierAmount: 2),
        new(
            "SFD·066/221",
            "封冻",
            2,
            "FREEZE_POWER_MINUS_2",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            EchoManaCost: 2,
            PowerModifierAmount: -2),
        new(
            "SFD·196/221",
            "距破之舞",
            1,
            "DISTANCE_BREAK_DANCE_POWER_PLUS_2_AND_MINUS_2",
            0,
            2,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 2,
            SecondaryPowerModifierAmount: -2),
        new(
            "SFD·151/221",
            "力量之缚",
            2,
            "POWER_BIND_TWO_FRIENDLY_POWER_PLUS_1",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyUnit,
            EchoManaCost: 2,
            PowerModifierAmount: 1),
        new(
            "SFD·097/221",
            "先打再问",
            1,
            "SHOOT_FIRST_POWER_PLUS_5",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 5),
        new(
            "OGN·207/298",
            "荣耀召唤",
            3,
            "GLORY_CALL_POWER_PLUS_3",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 3),
        new(
            "UNL-095/219",
            "视死如归",
            2,
            "LAST_STAND_FRIENDLY_POWER_PLUS_3",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyUnit,
            PowerModifierAmount: 3),
        new(
            "OGN·146/298",
            "痛殴",
            2,
            "BEATDOWN_READY_UNIT",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            ReadiesTarget: true),
        new(
            "SFD·204/221",
            "狩猎",
            1,
            "HUNT_READY_ALL_FRIENDLY_UNITS",
            0,
            0,
            ReadiesAllFriendlyUnits: true),
        new(
            "SFD·194/221",
            "反击风暴",
            2,
            "COUNTERSTORM_PREVENT_NEXT_DAMAGE_DRAW_1",
            0,
            1,
            StatusEffectId: "PREVENT_NEXT_DAMAGE_THIS_TURN",
            DrawCount: 1,
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "OGN·154/298",
            "洪荒巨力",
            4,
            "TREMENDOUS_STRENGTH_POWER_PLUS_7",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            PowerModifierAmount: 7),
        new(
            "UNL-128/219",
            "造化弄人",
            3,
            "HAPPENSTANCE_RETURN_FRIENDLY_AND_ENEMY_TO_HAND",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyThenEnemyUnits,
            ReturnsTargetToHand: true),
        new(
            "OGN·187/298",
            "飓风席卷",
            4,
            "HURRICANE_SWEEP_EACH_PLAYER_MAY_RETURN_UNIT",
            0,
            2,
            TargetScope: CardTargetScopes.AnyUnit,
            MinTargetCount: 0,
            ReturnsTargetToHand: true),
        new(
            "UNL-204/219",
            "持卫的裁决",
            2,
            "CUSTODIAN_JUDGMENT_ENEMY_BATTLEFIELD_UNIT_TO_TOP",
            0,
            1,
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit,
            Mode: "OWNER_MAIN_DECK_TOP",
            TargetOwnerMainDeckDestination: "TOP"),
        new(
            "UNL-204/219",
            "持卫的裁决",
            2,
            "CUSTODIAN_JUDGMENT_ENEMY_BATTLEFIELD_UNIT_TO_BOTTOM",
            0,
            1,
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit,
            Mode: "OWNER_MAIN_DECK_BOTTOM",
            TargetOwnerMainDeckDestination: "BOTTOM"),
        new(
            "OGN·104/298",
            "择日再战",
            1,
            "RECONSIDER_RETURN_FRIENDLY_CALL_RUNE",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyUnit,
            ReturnsTargetToHand: true,
            RuneCallCountAfterTargetReturn: 1),
        new(
            "OGN·144/298",
            "以战养战",
            4,
            "SPOILS_OF_WAR_DRAW_2",
            0,
            0,
            DrawCount: 2,
            CostReductionConditionKind: CardCostReductionConditionKinds.EnemyUnitDestroyedThisTurn,
            CostReductionMana: 2),
        new(
            "OGN·047/298",
            "御衡守念",
            3,
            "MIND_AND_BALANCE_DRAW_1_CALL_RUNE",
            0,
            0,
            DrawCount: 1,
            CostReductionConditionKind: CardCostReductionConditionKinds.OpponentWithinThreeOfWinningScore,
            CostReductionMana: 2,
            RuneCallCount: 1,
            DrawsBeforeRuneCall: true),
        new(
            "OGN·134/298",
            "动员",
            2,
            "MOBILIZE_CALL_RUNE_OR_DRAW",
            0,
            0,
            RuneCallCount: 1,
            DrawCountIfRuneCallFails: 1),
        new(
            "OGN·138/298",
            "万世催化石",
            4,
            "CATALYST_OF_AEONS_CALL_2_RUNES_OR_DRAW",
            0,
            0,
            RuneCallCount: 2,
            DrawCountIfRuneCallFails: 1),
        new(
            "OGN·201/298",
            "反转时间线",
            3,
            "REWIND_TIMELINE_DISCARD_HANDS_DRAW_4",
            0,
            0,
            DrawCount: 4,
            DiscardsAllPlayersHandsThenDraws: true),
        new(
            "OGN·172/298",
            "责退",
            2,
            "REPRIMAND_RETURN_BATTLEFIELD_UNIT_TO_HAND",
            0,
            1,
            ReturnsTargetToHand: true),
        new(
            "OGN·169/298",
            "罡风",
            1,
            "GUST_RETURN_BATTLEFIELD_UNIT_POWER_3_OR_LESS_TO_HAND",
            0,
            1,
            MaxTargetPower: 3,
            ReturnsTargetToHand: true),
        new(
            "OGN·168/298",
            "战或逃",
            2,
            "BATTLE_OR_FLIGHT_MOVE_BATTLEFIELD_UNIT_TO_BASE",
            0,
            1,
            MovesTargetToBase: true),
        new(
            "OGN·173/298",
            "驭风而行",
            2,
            "RIDE_THE_WIND_MOVE_FRIENDLY_BATTLEFIELD_UNIT_TO_BASE_READY",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyBattlefieldUnit,
            MovesTargetToBase: true,
            ReadiesTarget: true),
        new(
            "OGN·043/298",
            "魅惑妖术",
            1,
            "CHARM_MOVE_ENEMY_BATTLEFIELD_UNIT_TO_BASE",
            0,
            1,
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit,
            MovesTargetToBase: true),
        new(
            "UNL-038/219",
            "升龙踢",
            2,
            "RISING_DRAGON_KICK_MOVE_ENEMY_BATTLEFIELD_UNIT_TO_BASE_NO_LEVEL_6",
            0,
            1,
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit,
            MovesTargetToBase: true),
        new(
            "UNL-124/219",
            "隔绝",
            2,
            "ISOLATE_MOVE_ENEMY_BATTLEFIELD_UNIT_TO_BASE_NO_DRAW",
            0,
            1,
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit,
            MovesTargetToBase: true),
        new(
            "UNL-101/219",
            "战斗号令",
            3,
            "BATTLE_COMMAND_MOVE_FRIENDLY_AND_OPPONENT_UNIT_TO_BATTLEFIELD",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyThenEnemyUnits,
            MovesTargetsToOwnerBattlefields: true),
        new(
            "OGS·011/024",
            "闪现",
            2,
            "FLASH_MOVE_UP_TO_2_FRIENDLY_BATTLEFIELD_UNITS_TO_BASE",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyBattlefieldUnit,
            MinTargetCount: 0,
            MovesTargetToBase: true),
        new(
            "SFD·043/221",
            "禁军之墙",
            2,
            "SHIELD_WALL_MOVE_ANY_FRIENDLY_BATTLEFIELD_UNITS_TO_BASE",
            0,
            1,
            TargetScope: CardTargetScopes.FriendlyBattlefieldUnit,
            MinTargetCount: 0,
            MovesTargetToBase: true,
            UsesFriendlyBattlefieldUnitCountAsMaxTargetCount: true),
        new(
            "UNL-054/219",
            "顽皮触手",
            4,
            "PLAYFUL_TENTACLES_MOVE_ENEMY_BATTLEFIELD_UNITS_TOTAL_POWER_8_TO_BASE",
            0,
            8,
            TargetScope: CardTargetScopes.EnemyBattlefieldUnit,
            MinTargetCount: 0,
            MovesTargetToBase: true,
            MaxTotalTargetPower: 8),
        new(
            "SFD·129/221",
            "诱饵",
            2,
            "BAIT_MOVE_ENEMY_UNIT_TO_ANOTHER_ENEMY_UNIT_LOCATION_NO_ECHO",
            0,
            2,
            TargetScope: CardTargetScopes.EnemyUnitThenEnemyUnit,
            MovesFirstTargetToSecondTargetLocation: true),
        new(
            "OGN·022/298",
            "热电光束",
            5,
            "THERMOGENIC_BEAM_DESTROY_ALL_EQUIPMENT",
            0,
            0,
            DestroysAllEquipment: true),
        new(
            "SFD·135/221",
            "紧急召回",
            1,
            "EMERGENCY_RECALL_RETURN_EQUIPMENT_TO_HAND",
            0,
            1,
            TargetScope: CardTargetScopes.Equipment,
            ReturnsTargetToHand: true),
        new(
            "OGN·105/298",
            "星芒凝汇",
            6,
            "STELLAR_CONVERGENCE_DAMAGE_6_UP_TO_2",
            6,
            2,
            TargetScope: CardTargetScopes.AnyUnit,
            MinTargetCount: 1),
        new(
            "SFD·077/221",
            "火箭轰击",
            4,
            "ROCKET_BARRAGE_BASE_UNIT_DAMAGE_4",
            4,
            1,
            TargetScope: CardTargetScopes.BaseUnit,
            Mode: "BASE_UNIT_DAMAGE_4"),
        new(
            "SFD·077/221",
            "火箭轰击",
            4,
            "ROCKET_BARRAGE_DESTROY_EQUIPMENT",
            0,
            1,
            TargetScope: CardTargetScopes.Equipment,
            Mode: "DESTROY_EQUIPMENT",
            DestroysTarget: true),
        new(
            "SFD·080/221",
            "风箱炎息",
            1,
            "BELLOWS_BREATH_DAMAGE_1_UP_TO_3_SAME_LOCATION_NO_ECHO",
            1,
            3,
            TargetScope: CardTargetScopes.AnyUnit,
            MinTargetCount: 1),
        new(
            "UNL-044/219",
            "羽毛旋风",
            4,
            "FEATHERSTORM_CREATE_FOUR_WARHAWKS",
            0,
            0,
            Mode: "CREATE_WARHAWKS",
            CreatedBaseUnitTokenCount: 4,
            CreatedBaseUnitTokenPower: 1,
            CreatedBaseUnitTokenName: "战鹰",
            CreatedBaseUnitTokenTags: CardObjectTags.Spellshield),
        new(
            "SFD·076/221",
            "产量激增",
            4,
            "PRODUCTION_SURGE_CREATE_ROBOT_DRAW_1",
            0,
            0,
            DrawCount: 1,
            CostReductionConditionKind: CardCostReductionConditionKinds.ControllerControlsTaggedUnit,
            CostReductionMana: 2,
            CostReductionUnitTag: "机械",
            CreatedBaseUnitTokenCount: 1,
            CreatedBaseUnitTokenPower: 3,
            CreatedBaseUnitTokenName: "机器人"),
        new(
            "OGS·015/024",
            "共同献身",
            6,
            "COMMON_CAUSE_CREATE_FOUR_MINIONS_BASE",
            0,
            0,
            Mode: "BASE",
            CreatedBaseUnitTokenCount: 4,
            CreatedBaseUnitTokenPower: 1,
            CreatedBaseUnitTokenName: "随从"),
        new(
            "OGN·094/298",
            "精灵召唤",
            3,
            "SPRITE_SUMMON_CREATE_SPRITE_BASE",
            0,
            0,
            CreatedBaseUnitTokenCount: 1,
            CreatedBaseUnitTokenPower: 3,
            CreatedBaseUnitTokenName: "精灵",
            CreatedBaseUnitTokenTags: CardObjectTags.Ephemeral),
        new(
            "UNL-069/219",
            "精灵迸发",
            5,
            "SPRITE_BURST_CREATE_TWO_SPRITES_BASE",
            0,
            0,
            CreatedBaseUnitTokenCount: 2,
            CreatedBaseUnitTokenPower: 3,
            CreatedBaseUnitTokenName: "精灵",
            CreatedBaseUnitTokenTags: CardObjectTags.Ephemeral),
        new(
            "UNL-200/219",
            "镜花水月",
            3,
            "MIRROR_IMAGE_CREATE_COPY_EPHEMERAL_BASE",
            0,
            1,
            TargetScope: CardTargetScopes.AnyUnit,
            CreatedBaseUnitTokenCount: 1,
            CreatedBaseUnitTokenName: "映像",
            CreatedBaseUnitTokenTags: CardObjectTags.Ephemeral,
            CreatedBaseUnitTokenCopiesFirstTarget: true),
        new(
            "OGS·020/024",
            "高原血统",
            4,
            "HIGHLANDER_BLOODLINE_RECALL_IF_DESTROYED",
            0,
            1,
            StatusEffectId: "RECALL_TO_BASE_EXHAUSTED_IF_DESTROYED_THIS_TURN",
            TargetScope: CardTargetScopes.FriendlyUnit),
        new(
            "UNL-175/219",
            "战术撤退",
            2,
            "TACTICAL_RETREAT_RECALL_IF_DESTROYED",
            0,
            1,
            StatusEffectId: "RECALL_TO_BASE_EXHAUSTED_IF_DESTROYED_THIS_TURN",
            TargetScope: CardTargetScopes.FriendlyUnit),
        new(
            "SFD·031/221",
            "点沙成兵",
            2,
            "SANDCRAFT_CREATE_SAND_SOLDIER_ECHO",
            0,
            0,
            EchoManaCost: 2,
            CreatedBaseUnitTokenCount: 1,
            CreatedBaseUnitTokenPower: 2,
            CreatedBaseUnitTokenName: "黄沙士兵"),
        new(
            "SFD·154/221",
            "护驾！",
            3,
            "PROTECT_THE_EMPEROR_CREATE_SAND_SOLDIER",
            0,
            0,
            CreatedBaseUnitTokenCount: 1,
            CreatedBaseUnitTokenPower: 2,
            CreatedBaseUnitTokenName: "黄沙士兵"),
        new(
            "SFD·198/221",
            "沙兵现身",
            6,
            "SAND_SOLDIERS_RISE_READY_TWO_SAND_SOLDIERS_NO_WEAPONS",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyUnit,
            TargetRequiredTag: CardObjectTags.SandSoldier,
            ReadiesTarget: true),
        new(
            "OGN·024/298",
            "虚空索敌",
            3,
            "VOID_SEEKER_DAMAGE_4_DRAW_1",
            4,
            1,
            CardDamageConditionKinds.None,
            0,
            "",
            1),
        new(
            "OGN·206/298",
            "背靠背",
            3,
            "BACK_TO_BACK_TWO_FRIENDLY_POWER_PLUS_2",
            0,
            2,
            TargetScope: CardTargetScopes.FriendlyUnit,
            PowerModifierAmount: 2),
        new(
            "OGN·233/298",
            "宏伟战略",
            6,
            "GRAND_STRATEGY_ALL_FRIENDLY_POWER_PLUS_5",
            0,
            0,
            ModifiesAllFriendlyUnits: true,
            PowerModifierAmount: 5),
        new(
            "OGN·229/298",
            "复仇",
            4,
            "VENGEANCE_DESTROY_UNIT",
            0,
            1,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.AnyUnit),
        new(
            "UNL-186/219",
            "涌泉之恨",
            4,
            "WELLSPRING_OF_HATRED_DESTROY_BATTLEFIELD_UNIT",
            0,
            1,
            DestroysTarget: true,
            TargetScope: CardTargetScopes.BattlefieldUnit),
        new(
            "SFD·087/221",
            "先知之兆",
            2,
            "PROPHETS_OMEN_DRAW_3",
            0,
            0,
            DrawCount: 3),
        new(
            "SFD·106/221",
            "实力至上",
            2,
            "MIGHT_MAKES_RIGHT_DRAW_POWERFUL_UNITS",
            0,
            0,
            DynamicDrawCountKind: CardDynamicDrawCountKinds.ControllerPowerfulUnits),
        new(
            "OGN·114/298",
            "进化日",
            6,
            "EVOLUTION_DAY_DRAW_4",
            0,
            0,
            DrawCount: 4)
    ];

    public static bool TryGetByCardNo(string cardNo, out CardBehaviorDefinition definition)
    {
        definition = Definitions.FirstOrDefault(candidate => string.Equals(
            candidate.CardNo,
            cardNo,
            StringComparison.Ordinal))!;
        return definition is not null;
    }

    public static bool TryGetByCardNoAndMode(
        string cardNo,
        string mode,
        out CardBehaviorDefinition definition)
    {
        var normalizedMode = NormalizeMode(mode);
        definition = Definitions.FirstOrDefault(candidate =>
            string.Equals(candidate.CardNo, cardNo, StringComparison.Ordinal)
            && string.Equals(NormalizeMode(candidate.Mode), normalizedMode, StringComparison.Ordinal))!;
        return definition is not null;
    }

    public static bool TryGetByEffectKind(string effectKind, out CardBehaviorDefinition definition)
    {
        definition = Definitions.FirstOrDefault(candidate => string.Equals(
            candidate.EffectKind,
            effectKind,
            StringComparison.Ordinal))!;
        return definition is not null;
    }

    private static string NormalizeMode(string? mode)
    {
        return string.IsNullOrWhiteSpace(mode) ? string.Empty : mode.Trim();
    }
}
